image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 80
    onOpen: notify
  - port: 8080
    onOpen: notify

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
    - command: echo 'export PATH=/workspace/gitpod-code-tree/Environment/bin:$PATH' >> ~/.bashrc && chmod +x /workspace/gitpod-code-tree/Environment/makeexec.sh && /workspace/gitpod-code-tree/Environment/makeexec.sh && exit
